const express= require('express');

const { getCoupon, getCouponList, isCorrectCoupon, createOrder } = require('../controllers/orderController');



const  orderRoute  =express.Router();



orderRoute.get("/coupon",getCoupon)
//check the user is the suitable canditate for the coupon if he/she send the coupon



orderRoute.get("/couponList",getCouponList)
//get the coupons along with the discount generated by the coupon



orderRoute.get("/checkout/:couponId",isCorrectCoupon)
//check the coupon is correct or not




orderRoute.post("/order",createOrder)
//create an order


module.exports ={orderRoute}