import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import { useEffect } from 'react'
import axios from 'axios'
import { useDispatch ,useSelector} from 'react-redux'
import { addProduct } from '@/store/productReducers'
import { Button, Card, message } from 'antd'
import { add_product } from '../store/cartReducer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [messageApi, contextHolder] = message.useMessage(); //for earnings eror AND sucess
const Dispatch=useDispatch()
  


  useEffect(()=>{



    axios.get("http://localhost:3000/").then(res=>{  //fetch the product
      
    
    Dispatch(addProduct(res.data) // add the products to  products state
    
    )
    
  }).catch(err=>console.log(err))
    
    
   
    
    },[])

    const data =useSelector(state=>state) //get the state
   console.log(data);
const addTocart =(ele,quan)=>{

          Dispatch(add_product({...ele,quant:parseInt(quan)})) //add product to cart
          messageApi.success(`sucessfully added ${ele.name} to cart `,2)
     localStorage.setItem('cartuser',JSON.stringify(data.cart)) // refresh the localstorage with new cart




}



  return (
    <>
    {contextHolder} 
    {/* come from the antd message.usemessage to refractor */}
      <Head>
        <title>Discounted shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Navbar/>
   <div className={`flex flex-row flex-wrap  gap-6 justify-center w-full mt-12`}>
      { data.products && data.products.map((ele)=>{

            return( <Card  bordered={false} className="w-[300px] h-80"
            cover={<div className="w-full h-32"><img src={ele.imgLink} alt="ele.p"  className="w-full h-full object-cover"/></div>}
            >
            
    <p style={{fontSize:20,fontWeight:500}}>{ele.name}</p>
    <p>Rs {ele.price}</p>
<Button onClick={()=>{addTocart(ele,1)}}>add to cart</Button>
  </Card>)



      })}


   </div>
    </>
  )
}
