import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import { useEffect } from 'react'
import axios from 'axios'
import { useDispatch ,useSelector} from 'react-redux'
import { addProduct } from '@/store/productReducers'
import { Button, Card } from 'antd'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

const Dispatch=useDispatch()
  


  useEffect(()=>{



    axios.get("http://localhost:3000/").then(res=>{
      
    
    Dispatch(addProduct(res.data)
    
    )
    
  }).catch(err=>console.log(err))
    
    
   
    
    },[])
    const data =useSelector(state=>state.products)
    console.log(data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <Navbar/>
   <div style={{display:'flex',flexDirection:'row',columnGap:20}}>
      { data && data.map((ele)=>{

            return( <Card  bordered={false} style={{ width: 300 }}
            cover={<img src={ele.imgLink} alt="ele.p" height="300" style={{objectFit:'cover'}} />}
            >
            
    <p style={{fontSize:20,fontWeight:500}}>{ele.name}</p>
    <p>Rs {ele.price}</p>
<Button>add to cart</Button>
  </Card>)



      })}


   </div>
    </>
  )
}
